import test from "node:test"; import assert from "node:assert/strict";
process.env.DOTENV_CONFIG_PATH="test/does-not-exist.env";process.env.NODE_ENV="test";process.env.DATABASE_URL="postgresql://unused:unused@127.0.0.1:1/unused";process.env.JWT_SECRET="test-only-secret-0123456789-abcdefghijklmnopqrstuvwxyz";process.env.CORS_ORIGIN="http://localhost:5173";
const {assessmentInternals}=await import("../src/services/assessmentService.js");
const {normalizeGeneratedQuestions}=await import("../src/services/assessmentGenerationService.js");
const rows=[
 {question_id:1,prompt:"Select both primary colors",explanation:"Red and blue are expected.",question_position:1,points:2,option_id:11,option_text:"Red",is_correct:true,option_position:1},
 {question_id:1,prompt:"Select both primary colors",explanation:"Red and blue are expected.",question_position:1,points:2,option_id:12,option_text:"Blue",is_correct:true,option_position:2},
 {question_id:1,prompt:"Select both primary colors",explanation:"Red and blue are expected.",question_position:1,points:2,option_id:13,option_text:"Green",is_correct:false,option_position:3},
 {question_id:2,prompt:"Choose the runtime",explanation:"JavaScript runs in browsers.",question_position:2,points:1,option_id:21,option_text:"JavaScript",is_correct:true,option_position:1},
 {question_id:2,prompt:"Choose the runtime",explanation:"JavaScript runs in browsers.",question_position:2,points:1,option_id:22,option_text:"CSS",is_correct:false,option_position:2},
];
test("in-progress attempt payload preserves persisted order without correctness leakage",()=>{const questions=assessmentInternals.grouped(rows);const payload=assessmentInternals.publicAttempt({id:9,quiz_id:4,title:"Frontend",attempt_number:1,status:"in_progress",question_order:[2,1],option_orders:{"1":[13,11,12],"2":[22,21]}},questions,false);assert.deepEqual(payload.questions.map(q=>q.id),[2,1]);assert.deepEqual(payload.questions[1].options.map(o=>o.id),[13,11,12]);assert.doesNotMatch(JSON.stringify(payload),/isCorrect|correctOption|explanation/);});
test("grading requires exact answer sets and weighted points",()=>{const result=assessmentInternals.grade(assessmentInternals.grouped(rows),[{questionId:1,selectedOptionIds:[12,11]},{questionId:2,selectedOptionIds:[22]}]);assert.equal(result.earnedPoints,2);assert.equal(result.totalPoints,3);assert.equal(result.scorePercent,66.67);assert.equal(result.answers[0].isCorrect,true);assert.equal(result.answers[1].isCorrect,false);});
test("grading rejects missing questions, duplicate question submissions and foreign option ids",()=>{const questions=assessmentInternals.grouped(rows);for(const answers of [[{questionId:1,selectedOptionIds:[11,12]}],[{questionId:1,selectedOptionIds:[11,12]},{questionId:1,selectedOptionIds:[11,12]}],[{questionId:1,selectedOptionIds:[11,12]},{questionId:2,selectedOptionIds:[999]}]])assert.throws(()=>assessmentInternals.grade(questions,answers),error=>error.statusCode===400);});
test("AI question snapshots keep stable database ids and never leak answers before submission",()=>{const templates=[{id:1,points:1,options:[{id:11},{id:12},{id:13},{id:14}]}];const generated=normalizeGeneratedQuestions({questions:[{prompt:"Which Hook stores component state?",explanation:"useState stores local component state.",options:[{text:"useState",isCorrect:true},{text:"useEffect",isCorrect:false},{text:"fetch",isCorrect:false},{text:"memo",isCorrect:false}]}]},templates);const attempt={id:9,quiz_id:4,title:"React",attempt_number:1,status:"in_progress",generation_mode:"ai",question_order:[1],option_orders:{"1":[12,11,14,13]},question_snapshot:generated};const payload=assessmentInternals.publicAttempt(attempt,assessmentInternals.snapshotQuestions(attempt),false);assert.equal(payload.generatedByAI,true);assert.deepEqual(payload.questions[0].options.map(option=>option.id),[12,11,14,13]);assert.doesNotMatch(JSON.stringify(payload),/isCorrect|correctOption|explanation/);});
test("AI question validation rejects duplicate options and ambiguous correct answers",()=>{const templates=[{id:1,points:1,options:[{id:11},{id:12},{id:13},{id:14}]}];const base={prompt:"Valid prompt",explanation:"Valid explanation",options:[{text:"A",isCorrect:true},{text:"B",isCorrect:false},{text:"C",isCorrect:false},{text:"D",isCorrect:false}]};assert.throws(()=>normalizeGeneratedQuestions({questions:[{...base,options:[{text:"A",isCorrect:true},{text:"A",isCorrect:false},{text:"C",isCorrect:false},{text:"D",isCorrect:false}]}]},templates),/duplicate options/);assert.throws(()=>normalizeGeneratedQuestions({questions:[{...base,options:base.options.map(option=>({...option,isCorrect:false}))}]},templates),/exactly one correct/);});
