import{test}from"node:test";import assert from"node:assert/strict";import{scoreCareer}from"../src/services/careerMatchService.js";
const career=(overrides={})=>({id:"10",title:"Frontend Developer",slug:"frontend-developer",short_description:"Build interfaces",category_name:"Technology",experience_level:null,recommendation_summary:null,requirements:[{skillId:"1",name:"HTML/CSS",type:"required",targetLevel:3,importance:3},{skillId:"2",name:"JavaScript",type:"required",targetLevel:4,importance:3},{skillId:"3",name:"React",type:"recommended",targetLevel:3,importance:2}],...overrides});
const evidence=(overrides={})=>({verifiedSkillIds:[],quizPasses:[],challengePasses:[],approvedProjects:[],...overrides});
const readiness=(score=0,portfolio=0)=>({score,components:{portfolio:{score:portfolio}}});
test("career match exact arithmetic uses only relevant recorded evidence",()=>{const result=scoreCareer(career(),evidence({verifiedSkillIds:["1","3"],quizPasses:[{id:"q1",skill_id:"1"},{id:"q2",skill_id:"99"}],approvedProjects:[{project_id:"7",career_id:"10"}]}),readiness(55,8));assert.equal(result.components.verifiedSkills.score,25);assert.equal(result.components.assessments.score,5);assert.equal(result.components.projects.score,10);assert.equal(result.components.readiness.score,6);assert.equal(result.components.portfolio.score,8);assert.equal(result.matchPercent,54);assert.deepEqual(result.metRequirements.map(x=>x.name),["HTML/CSS","React"]);assert.deepEqual(result.missingRequirements.map(x=>x.name),["JavaScript"]);});
test("missing evidence produces zero without self-rating credit",()=>{const result=scoreCareer(career(),evidence({selfRatings:[{skillId:"1",level:5}]}),readiness());assert.equal(result.matchPercent,0);assert.equal(result.metRequirements.length,0);assert.equal(result.missingRequirements.length,3);});
test("component caps prevent duplicate evidence inflation",()=>{const result=scoreCareer(career(),evidence({verifiedSkillIds:["1","2","3","3"],quizPasses:Array.from({length:8},(_,i)=>({id:String(i),skill_id:"1"})),approvedProjects:Array.from({length:5},(_,i)=>({project_id:String(i),career_id:"10"}))}),readiness(100,10));assert.equal(result.matchPercent,100);assert.deepEqual(Object.values(result.components).map(x=>x.score),[40,20,20,10,10]);});
test("experience label is deterministic and explicit metadata wins",()=>{assert.equal(scoreCareer(career(),evidence(),readiness()).experienceLevel,"intermediate");assert.equal(scoreCareer(career({experience_level:"entry"}),evidence(),readiness()).experienceLevel,"entry");});
test("match payload contains explanations but no private evidence fields",()=>{const result=scoreCareer(career(),evidence({approvedProjects:[{project_id:"7",career_id:"10",repository_url:"https://private.example"}]}),readiness());const serialized=JSON.stringify(result);assert.doesNotMatch(serialized,/repository_url|private\.example|user_id|reviewer/);});
