import{test}from"node:test";import assert from"node:assert/strict";
process.env.DOTENV_CONFIG_PATH="test/does-not-exist.env";process.env.NODE_ENV="test";process.env.JWT_SECRET="test-only-secret-0123456789-abcdefghijklmnopqrstuvwxyz";process.env.DATABASE_URL="postgresql://unused:unused@127.0.0.1:1/unused";process.env.CORS_ORIGIN="http://localhost:5173";process.env.PUBLIC_APP_URL="https://learn.example.test";
const{evaluateEligibility,generateVerificationCode,buildVerificationUrl,publicVerification,renderCertificatePdf}=await import("../src/services/certificateService.js");
const definition={required_readiness_score:60,lessons:[{id:1,title:"Lesson"}],quizzes:[{id:2,title:"Quiz"}],projects:[{id:3,title:"Project"}]};
test("certificate eligibility reports every unmet configured requirement",()=>{const result=evaluateEligibility(definition,{lessonIds:[],quizIds:[],projectIds:[],readinessScore:35});assert.equal(result.eligible,false);assert.equal(result.missing.lessons.length,1);assert.equal(result.missing.quizzes.length,1);assert.equal(result.missing.projects.length,1);assert.equal(result.missing.readinessPoints,25);});
test("certificate eligibility accepts exact completion thresholds",()=>{assert.equal(evaluateEligibility(definition,{lessonIds:["1"],quizIds:[2],projectIds:[3],readinessScore:60}).eligible,true);});
test("verification codes carry 192 random bits in a URL-safe 32-character value",()=>{const codes=new Set(Array.from({length:100},generateVerificationCode));assert.equal(codes.size,100);for(const code of codes)assert.match(code,/^[A-Za-z0-9_-]{32}$/);});
test("public verification exposes only certificate fields and an accurate disclosure",()=>{const result=publicVerification({verification_code:"A".repeat(32),recipient_name_snapshot:"Ada",certificate_title_snapshot:"Web Foundations",issued_at:"2026-01-01T00:00:00Z",status:"active",revoked_at:null,revocation_reason:"private"});assert.doesNotMatch(JSON.stringify(result),/private/);assert.match(result.disclosure,/not an academic degree/);});
test("generated PDF contains a QR linking to the public verification route",async()=>{const code="B".repeat(32),url=buildVerificationUrl(code);assert.equal(url,`https://learn.example.test/certificates/verify/${code}`);const buffer=await renderCertificatePdf({recipientName:"Ada",title:"Web Foundations",issuedAt:"2026-01-01T00:00:00Z",status:"active",disclosure:"SkillForge completion only."},url);assert.equal(buffer.subarray(0,4).toString(),"%PDF");assert.ok(buffer.length>3000);});
