import {after,before,test,mock} from "node:test";import assert from "node:assert/strict";import{once}from"node:events";import jwt from"jsonwebtoken";
process.env.DOTENV_CONFIG_PATH="test/does-not-exist.env";process.env.NODE_ENV="test";process.env.JWT_SECRET="test-only-secret-0123456789-abcdefghijklmnopqrstuvwxyz";process.env.JWT_EXPIRES_IN="1h";process.env.DATABASE_URL="postgresql://unused:unused@127.0.0.1:1/unused";process.env.CORS_ORIGIN="http://localhost:5173";
const{pool}=await import("../src/config/db.js");const{default:app}=await import("../src/app.js");let server,base,status=null,reviewer=null,version=0,review=null,portfolioEntries=0;const learner=jwt.sign({sub:"1",email:"learner@test.dev"},process.env.JWT_SECRET,{algorithm:"HS256",expiresIn:"1h"});const admin=jwt.sign({sub:"2",email:"reviewer@test.dev"},process.env.JWT_SECRET,{algorithm:"HS256",expiresIn:"1h"});
function submission(){return{id:"10",user_id:"1",project_id:"7",status:status||"draft",reviewer_user_id:reviewer,current_version_id:version?String(100+version):null};}
function detail(){return{...submission(),project_title:"Portfolio",version_id:String(100+version),version,summary:"A complete accessible portfolio implementation.",repository_url:"https://github.com/example/project",demo_url:null,evidence_url:null,version_created_at:new Date().toISOString(),submitted_at:status&&status!=="draft"?new Date().toISOString():null,decision:review?.decision,feedback:review?.feedback,reviewed_at:review?new Date().toISOString():null,reviewer_name:review?"Reviewer":null,updated_at:new Date().toISOString()};}
async function query(sql,params=[]){const t=sql.replace(/\s+/g," ").trim();
if(t==="SELECT deleted_at FROM users WHERE id = $1")return{rows:[{deleted_at:null}]};
if(["BEGIN","COMMIT","ROLLBACK"].includes(t)||t.startsWith("INSERT INTO audit_logs")||t.startsWith("INSERT INTO project_submission_status_history")||t.startsWith("INSERT INTO portfolio_profiles"))return{rows:[]};if(t.startsWith("INSERT INTO portfolio_evidence_entries")){portfolioEntries+=1;return{rows:[]};}
if(t==="SELECT role FROM users WHERE id = $1")return{rows:[{role:String(params[0])==="2"?"content_admin":"learner"}]};if(t.startsWith("SELECT p.id,p.title,up.status"))return{rows:String(params[0])==="1"?[{id:"7",title:"Portfolio",user_status:"completed"}]:[]};if(t.startsWith("SELECT id,title FROM project_milestones"))return{rows:[{id:"501",title:"Build interface"}]};if(t.startsWith("SELECT * FROM project_submissions WHERE user_id"))return{rows:status?[submission()]:[]};if(t.startsWith("INSERT INTO project_submissions")){status="draft";return{rows:[submission()]};}if(t.startsWith("SELECT COALESCE(MAX(version)"))return{rows:[{version:version+1}]};if(t.startsWith("INSERT INTO project_submission_versions")){version+=1;return{rows:[{id:String(100+version),submission_id:"10",version}]};}if(t.startsWith("INSERT INTO project_submission_milestones"))return{rows:[]};if(t.startsWith("UPDATE project_submissions SET status='draft'")){status="draft";reviewer=null;return{rows:[]};}if(t.startsWith("SELECT ps.id,ps.user_id"))return{rows:[detail()]};if(t.startsWith("SELECT psm.project_milestone_id"))return{rows:[{project_milestone_id:"501",title:"Build interface",evidence_note:"Implemented",evidence_url:null}]};if(t.startsWith("SELECT h.from_status"))return{rows:[]};if(t.startsWith("SELECT * FROM project_submissions WHERE id=$1 AND user_id=$2"))return{rows:String(params[1])==="1"&&status?[submission()]:[]};if(t.startsWith("UPDATE project_submission_versions SET submitted_at"))return{rows:[]};if(t.startsWith("UPDATE project_submissions SET status='submitted'")){status="submitted";return{rows:[]};}if(t.startsWith("SELECT * FROM project_submissions WHERE id=$1 FOR UPDATE"))return{rows:status?[submission()]:[]};if(t.startsWith("UPDATE project_submissions SET status='under_review'")){status="under_review";reviewer=String(params[1]);return{rows:[submission()]};}if(t.startsWith("INSERT INTO project_submission_reviews")){review={decision:params[3],feedback:params[4],reviewer_user_id:String(params[2])};return{rows:[review]};}if(t.startsWith("UPDATE project_submissions SET status=$2")){status=params[1];return{rows:[]};}if(t.startsWith("SELECT * FROM project_submission_reviews"))return{rows:review?[review]:[]};throw new Error(`Unexpected submission SQL: ${t}`);}
before(async()=>{mock.method(pool,"query",query);mock.method(pool,"connect",async()=>({query,release(){}}));server=app.listen(0,"127.0.0.1");await once(server,"listening");base=`http://127.0.0.1:${server.address().port}/api`;});after(async()=>{await new Promise(resolve=>server.close(resolve));mock.restoreAll();await pool.end();});async function request(path,{method="GET",body,token}={}){const response=await fetch(base+path,{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,body:response.status===204?null:await response.json()};}
test("evidence validation rejects private and non-GitHub repository links before database work",async()=>{for(const repositoryUrl of["http://github.com/a/b","https://localhost/repo","https://gitlab.com/a/b"]){const r=await request("/project-submissions/projects/7/draft",{method:"POST",token:learner,body:{summary:"A sufficiently detailed project summary.",repositoryUrl,milestones:[]}});assert.equal(r.status,400);}});
test("learner saves an immutable evidence version and submits it",async()=>{const draft=await request("/project-submissions/projects/7/draft",{method:"POST",token:learner,body:{summary:"A complete accessible portfolio implementation.",repositoryUrl:"https://github.com/example/project",milestones:[{milestoneId:501,evidenceNote:"Implemented"}]}});assert.equal(draft.status,201);assert.equal(draft.body.submission.version.number,1);const submitted=await request("/project-submissions/10/submit",{method:"POST",token:learner});assert.equal(submitted.status,200);assert.equal(submitted.body.submission.status,"submitted");});
test("approval creates one private portfolio entry and repeated approval is idempotent",async()=>{assert.equal((await request("/project-submissions/review/queue",{token:learner})).status,403);assert.equal((await request("/project-submissions/review/10/claim",{method:"POST",token:admin})).status,200);const body={decision:"approved",feedback:"Evidence satisfies every required project milestone."};const approved=await request("/project-submissions/review/10/decision",{method:"POST",token:admin,body});assert.equal(approved.status,200);assert.equal(approved.body.submission.status,"approved");const repeated=await request("/project-submissions/review/10/decision",{method:"POST",token:admin,body});assert.equal(repeated.status,200);assert.equal(repeated.body.reused,true);assert.equal(portfolioEntries,1);});
test("submission write and review routes reject anonymous access",async()=>{for(const[method,path]of[["POST","/project-submissions/projects/7/draft"],["POST","/project-submissions/10/submit"],["GET","/project-submissions/mine"],["GET","/project-submissions/review/queue"]])assert.equal((await request(path,{method,...(method==="POST"?{body:{}}:{})})).status,401);});
