import{pool}from"../config/db.js";
export const wouldRemoveLastAdmin=(currentRole,nextRole,adminCount)=>currentRole==="admin"&&nextRole!=="admin"&&adminCount<=1;
export async function overview(){const r=await pool.query(`SELECT (SELECT count(*)::int FROM users) users,(SELECT count(*)::int FROM courses) courses,(SELECT count(*)::int FROM quizzes) quizzes,(SELECT count(*)::int FROM project_submissions WHERE status IN('submitted','under_review')) reviews,(SELECT count(*)::int FROM products) products,(SELECT count(*)::int FROM issued_certificates) certificates,(SELECT count(*)::int FROM withdrawal_requests WHERE status IN('pending','approved')) withdrawals`);return r.rows[0];}
export async function users({page,limit,search}){const value=search?`%${search}%`:null;const r=await pool.query(`SELECT id,name,email,role,created_at,COUNT(*) OVER()::int total FROM users WHERE $1::text IS NULL OR name ILIKE $1 OR email ILIKE $1 ORDER BY created_at DESC,id DESC LIMIT $2 OFFSET $3`,[value,limit,(page-1)*limit]);return r.rows;}
export async function setRole(actor,id,role){const client=await pool.connect();try{await client.query("BEGIN");const target=await client.query(`SELECT id,email,role FROM users WHERE id=$1 FOR UPDATE`,[id]);if(!target.rows[0]){await client.query("ROLLBACK");return null;}if(target.rows[0].role==="admin"&&role!=="admin"){const count=await client.query(`SELECT count(*)::int value FROM users WHERE role='admin'`);if(wouldRemoveLastAdmin(target.rows[0].role,role,count.rows[0].value)){await client.query("ROLLBACK");return{lastAdmin:true};}}const r=await client.query(`UPDATE users SET role=$2 WHERE id=$1 RETURNING id,name,email,role`,[id,role]);await client.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'user.role.updated','user',$2,$3::jsonb)`,[actor,id,JSON.stringify({from:target.rows[0].role,to:role})]);await client.query("COMMIT");return r.rows[0];}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function audits({page,limit,search}){const value=search?`%${search}%`:null;const r=await pool.query(`SELECT a.id,a.action,a.entity_type,a.entity_id,a.metadata,a.created_at,u.email actor_email,COUNT(*) OVER()::int total FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id WHERE $1::text IS NULL OR a.action ILIKE $1 OR a.entity_type ILIKE $1 OR u.email ILIKE $1 ORDER BY a.created_at DESC,a.id DESC LIMIT $2 OFFSET $3`,[value,limit,(page-1)*limit]);return r.rows;}
export async function policies(){const r=await pool.query(`SELECT * FROM commission_policies ORDER BY currency`);return r.rows;}
export async function upsertPolicy(actor,data){const r=await pool.query(`INSERT INTO commission_policies(currency,basis_points,hold_days,minimum_withdrawal_minor,is_active) VALUES($1,$2,$3,$4,$5) ON CONFLICT(currency) DO UPDATE SET basis_points=EXCLUDED.basis_points,hold_days=EXCLUDED.hold_days,minimum_withdrawal_minor=EXCLUDED.minimum_withdrawal_minor,is_active=EXCLUDED.is_active RETURNING *`,[data.currency,data.basisPoints,data.holdDays,data.minimumWithdrawalMinor,data.isActive]);await pool.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'commission_policy.updated','commission_policy',$2,$3::jsonb)`,[actor,r.rows[0].id,JSON.stringify({currency:data.currency})]);return r.rows[0];}
export default{overview,users,setRole,audits,policies,upsertPolicy};
