import{pool}from"../config/db.js";

export async function getActiveCareers(categoryId){const params=[];const category=categoryId?(params.push(categoryId),`AND c.category_id=$${params.length}`):"";const r=await pool.query(`SELECT c.id::text AS id,c.title,c.slug,c.short_description,c.experience_level,c.recommendation_summary,cc.name AS category_name,COALESCE(json_agg(json_build_object('skillId',s.id::text,'name',s.name,'type',cs.skill_type,'targetLevel',cs.target_level,'importance',cs.importance) ORDER BY cs.importance DESC,s.name) FILTER(WHERE s.id IS NOT NULL),'[]') AS requirements FROM careers c JOIN career_categories cc ON cc.id=c.category_id LEFT JOIN career_skills cs ON cs.career_id=c.id AND cs.skill_type IN('required','recommended') LEFT JOIN skills s ON s.id=cs.skill_id AND s.is_active=TRUE WHERE c.is_active=TRUE ${category} GROUP BY c.id,cc.name ORDER BY c.title`,params);return r.rows;}

export async function getVerifiedEvidence(userId){const[courseSkills,quizSkills,challengeSkills,projectSkills,quizPasses,challengePasses,approvedProjects]=await Promise.all([
  pool.query(`SELECT DISTINCT c.skill_id::text AS skill_id FROM course_enrollments ce JOIN courses c ON c.id=ce.course_id WHERE ce.user_id=$1 AND ce.status='completed'`,[userId]),
  pool.query(`SELECT DISTINCT COALESCE(q.skill_id,c.skill_id,lc.skill_id)::text AS skill_id FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id LEFT JOIN courses c ON c.id=q.course_id LEFT JOIN course_lessons cl ON cl.id=q.lesson_id LEFT JOIN course_modules cm ON cm.id=cl.module_id LEFT JOIN courses lc ON lc.id=cm.course_id WHERE qa.user_id=$1 AND qa.status='submitted' AND qa.passed=TRUE AND COALESCE(q.skill_id,c.skill_id,lc.skill_id) IS NOT NULL`,[userId]),
  pool.query(`SELECT DISTINCT cs.skill_id::text AS skill_id FROM user_challenge_progress ucp JOIN challenge_skills cs ON cs.challenge_id=ucp.challenge_id WHERE ucp.user_id=$1 AND ucp.status='completed'`,[userId]),
  pool.query(`SELECT DISTINCT psx.skill_id::text AS skill_id FROM project_submissions ps JOIN project_skills psx ON psx.project_id=ps.project_id LEFT JOIN project_submission_revocations r ON r.submission_id=ps.id WHERE ps.user_id=$1 AND ps.status='approved' AND r.id IS NULL`,[userId]),
  pool.query(`SELECT DISTINCT qa.quiz_id::text AS id,COALESCE(q.skill_id,c.skill_id,lc.skill_id)::text AS skill_id FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id LEFT JOIN courses c ON c.id=q.course_id LEFT JOIN course_lessons cl ON cl.id=q.lesson_id LEFT JOIN course_modules cm ON cm.id=cl.module_id LEFT JOIN courses lc ON lc.id=cm.course_id WHERE qa.user_id=$1 AND qa.status='submitted' AND qa.passed=TRUE`,[userId]),
  pool.query(`SELECT DISTINCT ucp.challenge_id::text AS id,cs.skill_id::text AS skill_id FROM user_challenge_progress ucp JOIN challenge_skills cs ON cs.challenge_id=ucp.challenge_id WHERE ucp.user_id=$1 AND ucp.status='completed'`,[userId]),
  pool.query(`SELECT DISTINCT ps.project_id::text AS project_id,cp.career_id::text AS career_id FROM project_submissions ps JOIN career_projects cp ON cp.project_id=ps.project_id LEFT JOIN project_submission_revocations r ON r.submission_id=ps.id WHERE ps.user_id=$1 AND ps.status='approved' AND r.id IS NULL`,[userId]),
]);return{verifiedSkillIds:[...courseSkills.rows,...quizSkills.rows,...challengeSkills.rows,...projectSkills.rows].map(x=>x.skill_id),quizPasses:quizPasses.rows,challengePasses:challengePasses.rows,approvedProjects:approvedProjects.rows};}

export async function getActions(careerIds,missingSkillIds){if(!careerIds.length)return{courses:[],projects:[]};const[courses,projects]=await Promise.all([
  missingSkillIds.length?pool.query(`SELECT DISTINCT ON(c.skill_id) c.id::text AS id,c.skill_id::text AS skill_id,c.title,c.slug FROM courses c WHERE c.status='published' AND c.skill_id=ANY($1::bigint[]) ORDER BY c.skill_id,c.is_premium,c.title`,[missingSkillIds]):Promise.resolve({rows:[]}),
  pool.query(`SELECT DISTINCT ON(cp.career_id) cp.career_id::text AS career_id,p.id::text AS id,p.title,p.slug FROM career_projects cp JOIN projects p ON p.id=cp.project_id WHERE cp.career_id=ANY($1::bigint[]) AND p.is_active=TRUE ORDER BY cp.career_id,cp.relevance DESC,p.title`,[careerIds]),
]);return{courses:courses.rows,projects:projects.rows};}
export default{getActiveCareers,getVerifiedEvidence,getActions};
