import { pool } from "../config/db.js";

const DEFINITION_SELECT = `SELECT d.id,d.title,d.slug,d.description,d.required_readiness_score,d.is_active,d.created_at,d.updated_at,
  COALESCE((SELECT jsonb_agg(jsonb_build_object('id',l.id,'title',l.title) ORDER BY l.id) FROM certificate_required_lessons r JOIN course_lessons l ON l.id=r.lesson_id WHERE r.definition_id=d.id),'[]'::jsonb) AS lessons,
  COALESCE((SELECT jsonb_agg(jsonb_build_object('id',q.id,'title',q.title) ORDER BY q.id) FROM certificate_required_quizzes r JOIN quizzes q ON q.id=r.quiz_id WHERE r.definition_id=d.id),'[]'::jsonb) AS quizzes,
  COALESCE((SELECT jsonb_agg(jsonb_build_object('id',p.id,'title',p.title) ORDER BY p.id) FROM certificate_required_projects r JOIN projects p ON p.id=r.project_id WHERE r.definition_id=d.id),'[]'::jsonb) AS projects
  FROM certificate_definitions d`;

export async function listDefinitions(activeOnly=false){const r=await pool.query(`${DEFINITION_SELECT}${activeOnly?" WHERE d.is_active=TRUE":""} ORDER BY d.title,d.id`);return r.rows;}
export async function getDefinition(id,activeOnly=false,client=pool){const r=await client.query(`${DEFINITION_SELECT} WHERE d.id=$1${activeOnly?" AND d.is_active=TRUE":""}`,[id]);return r.rows[0]||null;}

async function replaceRequirements(client,id,data){
  for(const [table,column,ids] of [["certificate_required_lessons","lesson_id",data.lessonIds],["certificate_required_quizzes","quiz_id",data.quizIds],["certificate_required_projects","project_id",data.projectIds]]){
    await client.query(`DELETE FROM ${table} WHERE definition_id=$1`,[id]);
    if(ids.length)await client.query(`INSERT INTO ${table}(definition_id,${column}) SELECT $1,unnest($2::bigint[])`,[id,ids]);
  }
}
export async function createDefinition(actorId,data){const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query(`INSERT INTO certificate_definitions(title,slug,description,required_readiness_score,is_active,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[data.title,data.slug,data.description??null,data.requiredReadinessScore,data.isActive,actorId]);await replaceRequirements(client,r.rows[0].id,data);await client.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'certificate.definition.created','certificate_definition',$2,$3::jsonb)`,[actorId,r.rows[0].id,JSON.stringify({slug:data.slug})]);await client.query("COMMIT");return getDefinition(r.rows[0].id,false);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function updateDefinition(actorId,id,data){const client=await pool.connect();try{await client.query("BEGIN");const current=await getDefinition(id,false,client);if(!current){await client.query("ROLLBACK");return null;}await client.query(`UPDATE certificate_definitions SET title=$2,slug=$3,description=$4,required_readiness_score=$5,is_active=$6 WHERE id=$1`,[id,data.title,data.slug,data.description??null,data.requiredReadinessScore,data.isActive]);await replaceRequirements(client,id,data);await client.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'certificate.definition.updated','certificate_definition',$2,$3::jsonb)`,[actorId,id,JSON.stringify({slug:data.slug})]);await client.query("COMMIT");return getDefinition(id,false);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}

export async function getEligibilityEvidence(userId,client=pool){const [lessons,quizzes,projects]=await Promise.all([
  client.query(`SELECT lesson_id::text AS id FROM lesson_progress WHERE user_id=$1`,[userId]),
  client.query(`SELECT DISTINCT quiz_id::text AS id FROM quiz_attempts WHERE user_id=$1 AND status='submitted' AND passed=TRUE`,[userId]),
  client.query(`SELECT DISTINCT ps.project_id::text AS id FROM project_submissions ps LEFT JOIN project_submission_revocations r ON r.submission_id=ps.id WHERE ps.user_id=$1 AND ps.status='approved' AND r.id IS NULL`,[userId]),
]);return{lessonIds:lessons.rows.map(x=>x.id),quizIds:quizzes.rows.map(x=>x.id),projectIds:projects.rows.map(x=>x.id)};}

const CERT_SELECT=`SELECT c.id,c.user_id,c.definition_id,c.verification_code,c.recipient_name_snapshot,c.certificate_title_snapshot,c.requirements_snapshot,c.readiness_snapshot_id,c.issued_at,c.status,c.revoked_at,c.revocation_reason FROM issued_certificates c`;
export async function listMine(userId){const r=await pool.query(`${CERT_SELECT} WHERE c.user_id=$1 ORDER BY c.issued_at DESC,c.id DESC`,[userId]);return r.rows;}
export async function findByCode(code){const r=await pool.query(`${CERT_SELECT} WHERE c.verification_code=$1`,[code]);return r.rows[0]||null;}
export async function findByIdForUser(id,userId){const r=await pool.query(`${CERT_SELECT} WHERE c.id=$1 AND c.user_id=$2`,[id,userId]);return r.rows[0]||null;}

export async function issue(userId,definitionId,code,snapshot,readinessSnapshotId){const client=await pool.connect();try{await client.query("BEGIN");await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${userId}:${definitionId}`]);await client.query(`SELECT id FROM certificate_definitions WHERE id=$1 FOR SHARE`,[definitionId]);const definition=await getDefinition(definitionId,true,client);if(!definition){await client.query("ROLLBACK");return{notFound:true};}const existing=await client.query(`${CERT_SELECT} WHERE c.user_id=$1 AND c.definition_id=$2 FOR UPDATE`,[userId,definitionId]);if(existing.rows[0]){await client.query("COMMIT");return{certificate:existing.rows[0],created:false};}const evidence=await getEligibilityEvidence(userId,client);const readiness=await client.query(`SELECT score FROM evidence_readiness_snapshots WHERE id=$1 AND user_id=$2`,[readinessSnapshotId,userId]);const has=(values,id)=>values.some(value=>String(value)===String(id));const unmet=(definition.lessons||[]).some(x=>!has(evidence.lessonIds,x.id))||(definition.quizzes||[]).some(x=>!has(evidence.quizIds,x.id))||(definition.projects||[]).some(x=>!has(evidence.projectIds,x.id))||Number(readiness.rows[0]?.score??-1)<Number(definition.required_readiness_score);if(unmet){await client.query("ROLLBACK");return{ineligible:true};}const user=await client.query(`SELECT name FROM users WHERE id=$1`,[userId]);const r=await client.query(`INSERT INTO issued_certificates(user_id,definition_id,verification_code,recipient_name_snapshot,certificate_title_snapshot,requirements_snapshot,readiness_snapshot_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) RETURNING *`,[userId,definitionId,code,user.rows[0].name,definition.title,JSON.stringify(snapshot),readinessSnapshotId]);await client.query(`INSERT INTO certificate_status_history(certificate_id,status,actor_user_id) VALUES($1,'issued',$2)`,[r.rows[0].id,userId]);await client.query("COMMIT");return{certificate:r.rows[0],created:true};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function revoke(id,actorId,reason){const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query(`UPDATE issued_certificates SET status='revoked',revoked_at=now(),revoked_by=$2,revocation_reason=$3 WHERE id=$1 AND status='active' RETURNING *`,[id,actorId,reason]);if(!r.rows[0]){const found=await client.query(`SELECT status FROM issued_certificates WHERE id=$1`,[id]);await client.query("ROLLBACK");return found.rows[0]?{alreadyRevoked:true}:null;}await client.query(`INSERT INTO certificate_status_history(certificate_id,status,actor_user_id,reason) VALUES($1,'revoked',$2,$3)`,[id,actorId,reason]);await client.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'certificate.revoked','issued_certificate',$2,$3::jsonb)`,[actorId,id,JSON.stringify({reason})]);await client.query("COMMIT");return r.rows[0];}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}

export default{listDefinitions,getDefinition,createDefinition,updateDefinition,getEligibilityEvidence,listMine,findByCode,findByIdForUser,issue,revoke};
