import{pool}from"../config/db.js";
export async function initiate(userId,orderId,reference){const client=await pool.connect();try{await client.query("BEGIN");const order=await client.query(`SELECT * FROM orders WHERE id=$1 AND user_id=$2 FOR UPDATE`,[orderId,userId]);if(!order.rows[0]){await client.query("ROLLBACK");return null;}if(order.rows[0].status!=="pending"){await client.query("ROLLBACK");return{invalidStatus:order.rows[0].status};}const payment=await client.query(`INSERT INTO payments(order_id,provider,status,provider_reference,amount_minor,currency) VALUES($1,'sandbox','pending',$2,$3,$4) ON CONFLICT(order_id) DO UPDATE SET order_id=EXCLUDED.order_id RETURNING *`,[orderId,reference,order.rows[0].total_minor,order.rows[0].currency]);await client.query("COMMIT");return{order:order.rows[0],payment:payment.rows[0]};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
const transitions={"payment.paid":["pending","paid"],"payment.failed":["pending","failed"],"payment.refunded":["paid","refunded"],"payment.disputed":["paid","disputed"]};
export async function applyEntitlementEffects(client,row,next){if(next==="paid"){
await client.query(`INSERT INTO access_grants(user_id,product_id,source,source_order_id,expires_at)
SELECT $1,oi.product_id,'purchase',$2,CASE WHEN p.product_type='subscription' THEN now()+(p.access_duration_days||' days')::interval END
FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=$2
ON CONFLICT(user_id,product_id) DO UPDATE SET source='purchase',source_order_id=$2,granted_at=now(),
expires_at=CASE WHEN EXCLUDED.expires_at IS NULL THEN NULL ELSE GREATEST(COALESCE(access_grants.expires_at,now()),now())+(SELECT access_duration_days||' days' FROM products WHERE id=EXCLUDED.product_id)::interval END,
revoked_at=NULL,revocation_reason=NULL
WHERE access_grants.revoked_at IS NOT NULL OR EXCLUDED.expires_at IS NOT NULL`,[row.user_id,row.order_id]);
await client.query(`INSERT INTO receipts(order_id,payment_id,receipt_number) VALUES($1,$2,$3) ON CONFLICT(order_id) DO NOTHING`,[row.order_id,row.id,`SF-${String(row.order_id).padStart(8,"0")}`]);}
if(next==="refunded"||next==="disputed")await client.query(`UPDATE access_grants g SET revoked_at=now(),revocation_reason=$3 WHERE g.user_id=$1 AND g.source='purchase' AND g.product_id IN(SELECT product_id FROM order_items WHERE order_id=$2) AND g.revoked_at IS NULL AND NOT EXISTS(SELECT 1 FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.product_id=g.product_id AND o.user_id=$1 AND o.status='paid' AND o.id<>$2)`,[row.user_id,row.order_id,`Order ${next}`]);}
export async function processEvent(event,hash){const client=await pool.connect();try{await client.query("BEGIN");const inserted=await client.query(`INSERT INTO payment_webhook_events(provider,provider_event_id,event_type,payload_sha256,payload) VALUES('sandbox',$1,$2,$3,$4::jsonb) ON CONFLICT(provider,provider_event_id) DO NOTHING RETURNING *`,[event.eventId,event.type,hash,JSON.stringify(event)]);if(!inserted.rows[0]){const prior=await client.query(`SELECT payload_sha256 FROM payment_webhook_events WHERE provider='sandbox' AND provider_event_id=$1`,[event.eventId]);await client.query("COMMIT");return prior.rows[0]?.payload_sha256===hash?{reused:true}:{errorCode:"event_id_payload_mismatch"};}const stored=inserted.rows[0];const payment=await client.query(`SELECT p.*,o.user_id,o.status AS order_status,o.total_minor,o.currency AS order_currency FROM payments p JOIN orders o ON o.id=p.order_id WHERE p.provider='sandbox' AND p.provider_reference=$1 FOR UPDATE OF p,o`,[event.providerReference]);const row=payment.rows[0];let errorCode=null;if(!row)errorCode="unknown_reference";else if(String(row.order_id)!==String(event.orderId)||Number(row.total_minor)!==Number(event.amountMinor)||row.order_currency!==event.currency)errorCode="payment_mismatch";const rule=transitions[event.type];if(!errorCode&&!rule)errorCode="unsupported_event";if(!errorCode&&row.status!==rule[0])errorCode=row.status===rule[1]?"duplicate_transition":"invalid_transition";if(errorCode){await client.query(`UPDATE payment_webhook_events SET processing_status=$2,error_code=$3,processed_at=now() WHERE id=$1`,[stored.id,errorCode==="duplicate_transition"?"processed":"rejected",errorCode]);await client.query("COMMIT");return{reused:errorCode==="duplicate_transition",errorCode};}const next=rule[1],timeColumn={paid:"paid_at",failed:"failed_at",refunded:"refunded_at",disputed:"disputed_at"}[next];await client.query(`UPDATE payments SET status=$2,provider_event_id=$3,${timeColumn}=now() WHERE id=$1`,[row.id,next,event.eventId]);await client.query(`UPDATE orders SET status=$2 WHERE id=$1`,[row.order_id,next==="failed"?"cancelled":next]);await client.query(`INSERT INTO payment_status_history(payment_id,from_status,to_status,webhook_event_id) VALUES($1,$2,$3,$4)`,[row.id,row.status,next,stored.id]);await applyEntitlementEffects(client,row,next);await client.query(`UPDATE payment_webhook_events SET processing_status='processed',processed_at=now() WHERE id=$1`,[stored.id]);await client.query("COMMIT");return{status:next,orderId:row.order_id};}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function getOrder(userId,id){const r=await pool.query(`SELECT o.*,p.id payment_id,p.status payment_status,p.provider_reference,r.receipt_number,r.issued_at,COALESCE(json_agg(json_build_object('productId',i.product_id,'name',i.product_name_snapshot,'amountMinor',i.unit_amount_minor) ORDER BY i.id),'[]') items FROM orders o JOIN order_items i ON i.order_id=o.id LEFT JOIN payments p ON p.order_id=o.id LEFT JOIN receipts r ON r.order_id=o.id WHERE o.id=$1 AND o.user_id=$2 GROUP BY o.id,p.id,r.id`,[id,userId]);return r.rows[0]||null;}
export default{initiate,processEvent,getOrder,applyEntitlementEffects};
