import { withContentAccess } from "./contentAccessService.js";
import crypto from "node:crypto";
import { ApiError } from "../middleware/errorHandler.js";
import * as model from "../models/assessmentModel.js";
import { requireEntityAccess } from "./commerceService.js";
import { createAttemptQuestionSet } from "./assessmentGenerationService.js";

function quizPublic(row){return{id:row.id,title:row.title,description:row.description,courseId:row.course_id,lessonId:row.lesson_id,skillId:row.skill_id,version:row.version,passPercent:row.pass_percent,maxAttempts:row.max_attempts,cooldownMinutes:row.cooldown_minutes,questionCount:row.question_count};}
function asJson(value,fallback){if(value==null)return fallback;if(typeof value==="string")return JSON.parse(value);return value;}
function grouped(rows){const map=new Map();for(const row of rows){if(!map.has(String(row.question_id)))map.set(String(row.question_id),{id:row.question_id,prompt:row.prompt,explanation:row.explanation,position:row.question_position,points:row.points,options:[]});map.get(String(row.question_id)).options.push({id:row.option_id,text:row.option_text,isCorrect:row.is_correct,position:row.option_position});}return [...map.values()];}
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=crypto.randomInt(i+1);[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function publicAttempt(attempt,questions,includeCorrect=false){const order=asJson(attempt.question_order,[]).map(String);const optionOrders=asJson(attempt.option_orders,{});const byId=new Map(questions.map(q=>[String(q.id),q]));const generationMode=attempt.generation_mode||"reviewed";return{id:attempt.id,quizId:attempt.quiz_id,title:attempt.title,attemptNumber:attempt.attempt_number,status:attempt.status,scorePercent:attempt.score_percent==null?null:Number(attempt.score_percent),passed:attempt.passed,startedAt:attempt.started_at,submittedAt:attempt.submitted_at,generationMode,generatedByAI:generationMode==="ai",questions:order.map(id=>{const q=byId.get(id);const optionOrder=(optionOrders[id]||[]).map(String);const optionsById=new Map(q.options.map(o=>[String(o.id),o]));return{id:q.id,prompt:q.prompt,points:q.points,...(includeCorrect?{explanation:q.explanation,correctOptionIds:q.options.filter(o=>o.isCorrect).map(o=>o.id)}:{}),options:optionOrder.map(optionId=>{const o=optionsById.get(optionId);return{id:o.id,text:o.text};})};})};}
function snapshotQuestions(attempt){const value=asJson(attempt.question_snapshot,null);return Array.isArray(value)&&value.length?value:null;}
async function questionsForAttempt(attempt,client){return snapshotQuestions(attempt)||grouped(await model.getVersionQuestions(attempt.quiz_version_id,client));}

export async function listQuizzes(filters,userId=null){const rows=await model.listPublished(filters);const total=rows[0]?.total||0;return{quizzes:await withContentAccess(rows.map(quizPublic),userId,"quiz"),pagination:{page:filters.page,limit:filters.limit,total,totalPages:Math.ceil(total/filters.limit)}};}
export async function getQuiz(quizId,userId){const quiz=await model.getPublishedQuiz(quizId,userId);if(!quiz)throw new ApiError(404,"Quiz not found.");const [access]=await withContentAccess([quizPublic(quiz)],userId,"quiz");return{quiz:{...access,requiresEnrollment:access.hasAccess&&!quiz.has_access,hasAccess:access.hasAccess&&Boolean(quiz.has_access)}};}
export async function startAttempt(userId,quizId){await requireEntityAccess(userId,"quiz",quizId);const quiz=await model.getPublishedQuiz(quizId,userId);if(!quiz)throw new ApiError(404,"Quiz not found.");if(!quiz.has_access)throw new ApiError(403,"Enroll in the linked course before starting this quiz.");const active=await model.getActiveAttempt(userId,quizId);if(active){const attempt={...active,title:quiz.title};return{attempt:publicAttempt(attempt,await questionsForAttempt(active),false),reused:true};}const templates=grouped(await model.getVersionQuestions(quiz.quiz_version_id));if(!templates.length)throw new ApiError(409,"This quiz has no published questions.");const generated=await createAttemptQuestionSet(quiz,templates);const questions=generated.questions;const questionOrder=shuffle(questions.map(q=>q.id));const optionOrders=Object.fromEntries(questions.map(q=>[q.id,shuffle(q.options.map(o=>o.id))]));const started=await model.beginAttempt(userId,quiz,questionOrder,optionOrders,{mode:generated.mode,provider:generated.provider,model:generated.model,questions:generated.mode==="ai"?questions:null});if(started.limit)throw new ApiError(409,"You have used every allowed attempt for this quiz.");if(started.cooldownUntil)throw new ApiError(429,"Wait until the quiz cooldown ends before trying again.",[{field:"cooldownUntil",message:started.cooldownUntil.toISOString()}]);const savedQuestions=started.reused?await questionsForAttempt(started.attempt):questions;const attempt={...started.attempt,title:quiz.title};return{attempt:publicAttempt(attempt,savedQuestions,false),reused:Boolean(started.reused)};}
export async function getAttempt(userId,id){const attempt=await model.getAttempt(id,userId);if(!attempt)throw new ApiError(404,"Quiz attempt not found.");await requireEntityAccess(userId,"quiz",attempt.quiz_id);const questions=await questionsForAttempt(attempt);const answers=attempt.status==="submitted"?(await model.getStoredAnswers(id)).map(a=>({questionId:a.question_id,selectedOptionIds:asJson(a.selected_option_ids,[]),isCorrect:a.is_correct,earnedPoints:a.earned_points})):undefined;return{attempt:publicAttempt(attempt,questions,attempt.status==="submitted"),...(answers?{answers}:{})};}
function grade(questions,submitted){const byQuestion=new Map(submitted.map(a=>[String(a.questionId),a]));if(byQuestion.size!==questions.length||questions.some(q=>!byQuestion.has(String(q.id))))throw new ApiError(400,"Submit one answer for every quiz question.");let earnedPoints=0,totalPoints=0;const answers=questions.map(q=>{const answer=byQuestion.get(String(q.id));const allowed=new Set(q.options.map(o=>String(o.id)));if(answer.selectedOptionIds.some(id=>!allowed.has(String(id))))throw new ApiError(400,"One or more selected options do not belong to that question.");const selected=[...answer.selectedOptionIds].map(String).sort();const correct=q.options.filter(o=>o.isCorrect).map(o=>String(o.id)).sort();const isCorrect=selected.length===correct.length&&selected.every((id,index)=>id===correct[index]);totalPoints+=q.points;if(isCorrect)earnedPoints+=q.points;return{questionId:q.id,selectedOptionIds:answer.selectedOptionIds,isCorrect,earnedPoints:isCorrect?q.points:0};});const scorePercent=totalPoints?Number((earnedPoints/totalPoints*100).toFixed(2)):0;return{answers,earnedPoints,totalPoints,scorePercent};}
export async function submitAttempt(userId,id,submitted){return model.withTransaction(async client=>{const attempt=await model.getAttempt(id,userId,client,true);if(!attempt)throw new ApiError(404,"Quiz attempt not found.");await requireEntityAccess(userId,"quiz",attempt.quiz_id);const questions=await questionsForAttempt(attempt,client);if(attempt.status==="submitted"){const stored=await model.getStoredAnswers(id,client);return{attempt:publicAttempt(attempt,questions,true),answers:stored.map(a=>({questionId:a.question_id,selectedOptionIds:asJson(a.selected_option_ids,[]),isCorrect:a.is_correct,earnedPoints:a.earned_points})),reused:true};}const result=grade(questions,submitted);result.passed=result.scorePercent>=Number(attempt.pass_percent);const saved=await model.saveSubmission(id,result.answers,result,client);return{attempt:publicAttempt({...attempt,...saved},questions,true),answers:result.answers,reused:false};});}
export async function history(userId){const rows=await model.listHistory(userId);return{attempts:rows.map(r=>({id:r.id,quizId:r.quiz_id,title:r.title,version:r.version,attemptNumber:r.attempt_number,scorePercent:r.score_percent==null?null:Number(r.score_percent),passed:r.passed,startedAt:r.started_at,submittedAt:r.submitted_at,generationMode:r.generation_mode||"reviewed"}))};}
export async function createQuiz(actorId,data){const result=await model.createQuiz(actorId,data);await model.audit(actorId,"quiz.create",result.quiz.id,{version:1});return{quiz:{id:result.quiz.id,title:result.quiz.title,courseId:result.quiz.course_id,lessonId:result.quiz.lesson_id,skillId:result.quiz.skill_id,version:result.version.version,description:result.version.description,passPercent:result.version.pass_percent,maxAttempts:result.version.max_attempts,cooldownMinutes:result.version.cooldown_minutes,status:result.version.status}};}
export async function addQuestion(actorId,quizId,data){const question=await model.addQuestion(quizId,data);if(!question)throw new ApiError(409,"Create or open a draft quiz version before adding questions.");await model.audit(actorId,"quiz.question.create",quizId,{questionId:question.id});return{question};}
export async function replaceQuestion(actorId,questionId,data){const result=await model.replaceQuestion(questionId,data);if(!result)throw new ApiError(409,"Only questions in a draft version can be changed.");await model.audit(actorId,"quiz.question.update",result.quizId,{questionId});return{question:result.question};}
export async function deleteQuestion(actorId,questionId){const result=await model.deleteQuestion(questionId);if(!result)throw new ApiError(409,"Only questions in a draft version can be removed.");await model.audit(actorId,"quiz.question.delete",result.quiz_id,{questionId});}
export async function publish(actorId,quizId){const version=await model.publish(quizId);if(!version)throw new ApiError(404,"Draft quiz not found.");if(version.invalid)throw new ApiError(409,"Add at least one valid question before publishing.");await model.audit(actorId,"quiz.publish",quizId,{version:version.version});return{version};}
export async function newVersion(actorId,quizId){const result=await model.cloneVersion(quizId);if(!result)throw new ApiError(404,"Published quiz not found.");await model.audit(actorId,"quiz.version.create",quizId,{version:(result.version||result.existing).version});return result;}
export async function adminDetail(quizId){const quiz=await model.getAdminQuiz(quizId);if(!quiz)throw new ApiError(404,"Quiz not found.");const questions=grouped(await model.getVersionQuestions(quiz.quiz_version_id));return{quiz:{...quizPublic(quiz),status:quiz.status,questions:questions.map(q=>({...q,options:q.options.map(o=>({id:o.id,text:o.text,isCorrect:o.isCorrect,position:o.position}))}))}};}
export async function adminList(){return{quizzes:(await model.listAdmin()).map(row=>({...quizPublic(row),status:row.status}))};}

export const assessmentInternals={grouped,grade,publicAttempt,snapshotQuestions};
