import { withContentAccess } from "./contentAccessService.js";
import { randomBytes } from "node:crypto";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { ApiError } from "../middleware/errorHandler.js";
import { env } from "../config/env.js";
import * as model from "../models/certificateModel.js";
import * as readinessService from "./evidenceReadinessService.js";
import { requireEntityAccess } from "./commerceService.js";

const ids=value=>new Set((value||[]).map(String));
export function evaluateEligibility(definition,evidence){const completedLessons=ids(evidence.lessonIds),passedQuizzes=ids(evidence.quizIds),approvedProjects=ids(evidence.projectIds);const missing={lessons:(definition.lessons||[]).filter(x=>!completedLessons.has(String(x.id))),quizzes:(definition.quizzes||[]).filter(x=>!passedQuizzes.has(String(x.id))),projects:(definition.projects||[]).filter(x=>!approvedProjects.has(String(x.id))),readinessPoints:Math.max(0,Number(definition.required_readiness_score)-Number(evidence.readinessScore||0))};return{eligible:!missing.lessons.length&&!missing.quizzes.length&&!missing.projects.length&&!missing.readinessPoints,missing,readinessScore:Number(evidence.readinessScore||0),requiredReadinessScore:Number(definition.required_readiness_score)};}
export const generateVerificationCode=()=>randomBytes(24).toString("base64url");
const mapCertificate=row=>({id:row.id,definitionId:row.definition_id,verificationCode:row.verification_code,recipientName:row.recipient_name_snapshot,title:row.certificate_title_snapshot,requirements:row.requirements_snapshot,issuedAt:row.issued_at,status:row.status,revokedAt:row.revoked_at});
const mapDefinition=(row,eligibility)=>({id:row.id,title:row.title,slug:row.slug,description:row.description,requiredReadinessScore:Number(row.required_readiness_score),isActive:row.is_active,lessons:row.lessons,quizzes:row.quizzes,projects:row.projects,...(eligibility?{eligibility}:{})});
async function currentEvidence(userId){const [base,readiness]=await Promise.all([model.getEligibilityEvidence(userId),readinessService.overview(userId)]);return{...base,readinessScore:readiness.score,readinessSnapshotId:readiness.snapshotId};}
export async function catalog(userId){const [definitions,evidence,issued]=await Promise.all([model.listDefinitions(true),currentEvidence(userId),model.listMine(userId)]);const issuedByDefinition=new Map(issued.map(x=>[String(x.definition_id),mapCertificate(x)]));return withContentAccess(definitions.map(row=>({...mapDefinition(row,evaluateEligibility(row,evidence)),certificate:issuedByDefinition.get(String(row.id))||null})),userId,"certificate");}
export async function mine(userId){return(await model.listMine(userId)).map(mapCertificate);}
export async function issue(userId,definitionId){await requireEntityAccess(userId,"certificate",definitionId);const definition=await model.getDefinition(definitionId,true);if(!definition)throw new ApiError(404,"Certificate program not found.");const evidence=await currentEvidence(userId);const eligibility=evaluateEligibility(definition,evidence);if(!eligibility.eligible)throw new ApiError(409,"Certificate requirements have not been met.",eligibility.missing);const snapshot={definition:mapDefinition(definition),evidence:{lessonIds:evidence.lessonIds,quizIds:evidence.quizIds,projectIds:evidence.projectIds,readinessScore:evidence.readinessScore},evaluatedAt:new Date().toISOString()};const result=await model.issue(userId,definitionId,generateVerificationCode(),snapshot,evidence.readinessSnapshotId);if(result.notFound)throw new ApiError(404,"Certificate program not found.");if(result.ineligible)throw new ApiError(409,"Certificate eligibility changed. Refresh and try again.");return{certificate:mapCertificate(result.certificate),created:result.created};}
export async function createDefinition(actorId,data){return mapDefinition(await model.createDefinition(actorId,data));}
export async function updateDefinition(actorId,id,data){const result=await model.updateDefinition(actorId,id,data);if(!result)throw new ApiError(404,"Certificate program not found.");return mapDefinition(result);}
export async function adminDefinitions(){return(await model.listDefinitions(false)).map(row=>mapDefinition(row));}
export async function revoke(id,actorId,reason){const result=await model.revoke(id,actorId,reason);if(!result)throw new ApiError(404,"Certificate not found.");if(result.alreadyRevoked)throw new ApiError(409,"Certificate is already revoked.");return mapCertificate(result);}
export function buildVerificationUrl(code){return `${env.publicAppUrl.replace(/\/$/,"")}/certificates/verify/${encodeURIComponent(code)}`;}
export function publicVerification(row){if(!row)throw new ApiError(404,"No certificate was found for that verification code.");return{verificationCode:row.verification_code,recipientName:row.recipient_name_snapshot,title:row.certificate_title_snapshot,issuedAt:row.issued_at,status:row.status,revokedAt:row.revoked_at,disclosure:"This verifies a SkillForge completion certificate. It is not an academic degree, professional license, or accredited qualification."};}
export async function verify(code){return publicVerification(await model.findByCode(code));}
export async function renderCertificatePdf(verification,url){const qr=await QRCode.toBuffer(url,{type:"png",width:220,margin:1,errorCorrectionLevel:"M"});const doc=new PDFDocument({size:"A4",layout:"landscape",margin:48,info:{Title:`SkillForge completion certificate - ${verification.recipientName}`,Author:"SkillForge AI"}});const chunks=[];doc.on("data",chunk=>chunks.push(chunk));const done=new Promise((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);});doc.rect(18,18,806,559).lineWidth(3).stroke("#5b4bdb");doc.fillColor("#17213c").fontSize(18).text("SKILLFORGE AI",0,70,{align:"center"});doc.moveDown().fontSize(34).text("SkillForge completion certificate",{align:"center"});doc.moveDown().fontSize(16).fillColor("#526078").text("Presented to",{align:"center"});doc.moveDown(0.5).fontSize(30).fillColor("#17213c").text(verification.recipientName,{align:"center"});doc.moveDown(0.6).fontSize(18).text(`for completing ${verification.title}`,{align:"center"});doc.moveDown().fontSize(12).fillColor(verification.status==="active"?"#176b5b":"#a33a3a").text(verification.status==="active"?"Status: Active":"Status: Revoked",{align:"center"});doc.fillColor("#526078").fontSize(10).text(`Issued ${new Date(verification.issuedAt).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric",timeZone:"UTC"})}`,70,485);doc.image(qr,665,390,{width:105});doc.text("Scan to verify",650,500,{width:135,align:"center"});doc.fontSize(8).text(url,70,530,{width:560});doc.fontSize(8).text(verification.disclosure,70,548,{width:600});doc.end();return done;}
export async function pdf(code){const row=await model.findByCode(code);const verification=publicVerification(row);const buffer=await renderCertificatePdf(verification,buildVerificationUrl(code));return{buffer,filename:`skillforge-certificate-${code.slice(0,8)}.pdf`};}
export default{catalog,mine,issue,verify,pdf,revoke,adminDefinitions,createDefinition,updateDefinition,evaluateEligibility,buildVerificationUrl};
