import { env } from "../config/env.js";
import { ApiError } from "../middleware/errorHandler.js";import * as model from "../models/commerceModel.js";
const money=row=>({currency:row.currency,amountMinor:Number(row.amount_minor)});
export function calculateSavings(priceMinor,individualValueMinor){return Math.max(0,Number(individualValueMinor)-Number(priceMinor));}
export async function catalog(currency,userId=null){return(await model.catalog(currency,userId)).map(row=>({id:row.id,name:row.name,slug:row.slug,description:row.description,kind:row.product_type,accessDurationDays:row.access_duration_days?Number(row.access_duration_days):null,price:money(row),individualValueMinor:Number(row.individual_value_minor),savingsMinor:row.product_type==='subscription'?0:calculateSavings(row.amount_minor,row.individual_value_minor),manualPrice:row.manual_amount_minor?{currency:"PKR",amountMinor:Number(row.manual_amount_minor)}:null,checkoutAvailable:env.nodeEnv==="test"?Boolean(env.sandboxPaymentWebhookSecret):Boolean(row.manual_enabled&&row.manual_amount_minor),skills:row.skills,hasAccess:Boolean(row.has_access),includes:{courses:row.courses,assessments:row.assessments,projects:row.projects,certificates:row.certificates}}));}
export async function accessProducts(type,id){return(await model.accessProducts(type,id)).map(row=>({id:row.id,name:row.name,slug:row.slug,kind:row.product_type,price:money(row)}));}
export function calculateQuote(products,discount){const subtotal=products.reduce((sum,p)=>sum+Number(p.amount_minor),0);const discountMinor=discount?Math.min(subtotal,discount.percent_off?Math.floor(subtotal*discount.percent_off/100):Number(discount.amount_off_minor)):0;return{subtotalMinor:subtotal,discountMinor,totalMinor:subtotal-discountMinor};}
export async function quote(data){const products=await model.productsForOrder(data.productIds,data.currency);if(products.length!==data.productIds.length)throw new ApiError(409,"One or more products are unavailable in that currency.");const discount=await model.discount(data.discountCode,data.currency);if(data.discountCode&&!discount)throw new ApiError(400,"Discount code is invalid or unavailable.");return{currency:data.currency,items:products.map(p=>({productId:p.id,name:p.name,amountMinor:Number(p.amount_minor)})),...calculateQuote(products,discount)};}
export async function createOrder(userId,data){const result=await model.createOrder(userId,data.productIds,data.currency,data.discountCode);if(result.unavailable)throw new ApiError(409,"One or more products are unavailable in that currency.");if(result.invalidDiscount)throw new ApiError(400,"Discount code is invalid or unavailable.");return{order:{id:result.order.id,status:result.order.status,currency:result.order.currency,subtotalMinor:Number(result.order.subtotal_minor),discountMinor:Number(result.order.discount_minor),totalMinor:Number(result.order.total_minor),items:result.items.map(p=>({productId:p.id,name:p.name,amountMinor:Number(p.amount_minor)})),message:"Order created. Access is granted only after a verified payment event in the payment phase."}};}
export async function account(userId){const[orders,grants]=await Promise.all([model.history(userId),model.grants(userId)]);return{orders:orders.map(o=>({id:o.id,status:o.status,currency:o.currency,subtotalMinor:Number(o.subtotal_minor),discountMinor:Number(o.discount_minor),totalMinor:Number(o.total_minor),createdAt:o.created_at,items:o.items})),access:grants.map(g=>({productId:g.product_id,name:g.name,slug:g.slug,kind:g.product_type,source:g.source,grantedAt:g.granted_at,expiresAt:g.expires_at})),refundPolicy:"Refunded or disputed orders revoke the associated purchase access through audited payment processing."};}
export async function requireEntityAccess(userId,type,id){if(!await model.hasEntityAccess(userId,type,id))throw new ApiError(403,"Permanent access is required for this premium content.");}
export const hasEntityAccess=(userId,type,id)=>model.hasEntityAccess(userId,type,id);
export async function requireLessonAccess(userId,lessonId){if(!await model.hasLessonAccess(userId,lessonId))throw new ApiError(403,"Permanent access is required for this premium lesson.");}
export const adminProducts=()=>model.adminProducts();export const createProduct=(actor,data)=>model.createProduct(actor,data);
export async function updateProduct(actor,id,data){const result=await model.updateProduct(actor,id,data);if(!result)throw new ApiError(404,"Product not found.");return result;}
export default{catalog,accessProducts,quote,createOrder,account,hasEntityAccess,requireEntityAccess,requireLessonAccess,adminProducts,createProduct,calculateQuote,calculateSavings};
