import{createHash,createHmac,randomBytes,timingSafeEqual}from"node:crypto";import{ApiError}from"../middleware/errorHandler.js";import{env}from"../config/env.js";import*as model from"../models/paymentModel.js";
import{paymentWebhookEventSchema}from"../utils/validation.js";
const configured=()=>{if(!env.sandboxPaymentWebhookSecret)throw new ApiError(503,"Sandbox payment processing is not configured.");};
export function signPayload(raw,timestamp,secret){return createHmac("sha256",secret).update(`${timestamp}.`).update(raw).digest("hex");}
export function verifySignature(raw,timestamp,header,secret,now=Date.now()){if(!raw||!timestamp||!header||!secret)return false;const seconds=Number(timestamp);if(!Number.isFinite(seconds)||Math.abs(Math.floor(now/1000)-seconds)>300)return false;const supplied=header.startsWith("sha256=")?header.slice(7):header;if(!/^[a-f0-9]{64}$/i.test(supplied))return false;const expected=signPayload(raw,timestamp,secret);return timingSafeEqual(Buffer.from(supplied,"hex"),Buffer.from(expected,"hex"));}
export async function initiate(userId,orderId){configured();if(env.nodeEnv!=="test")throw new ApiError(404,"Route not found.");const result=await model.initiate(userId,orderId,`sbx_${randomBytes(18).toString("hex")}`);if(!result)throw new ApiError(404,"Order not found.");if(result.invalidStatus)throw new ApiError(409,"Only pending orders can enter checkout.");return{orderId:result.order.id,status:result.payment.status,provider:"sandbox",providerReference:result.payment.provider_reference,amountMinor:Number(result.payment.amount_minor),currency:result.payment.currency,disclosure:"Sandbox checkout uses no real money or card information."};}
export async function webhook(raw,timestamp,signature){configured();if(env.nodeEnv!=="test")throw new ApiError(404,"Route not found.");if(!verifySignature(raw,timestamp,signature,env.sandboxPaymentWebhookSecret))throw new ApiError(401,"Invalid webhook signature.");let parsed;try{parsed=JSON.parse(raw.toString("utf8"));}catch{throw new ApiError(400,"Webhook body must contain valid JSON.");}const checked=paymentWebhookEventSchema.safeParse(parsed);if(!checked.success)throw new ApiError(400,"Invalid payment event.");const event=checked.data;const result=await model.processEvent(event,createHash("sha256").update(raw).digest("hex"));if(result.errorCode&&!result.reused)throw new ApiError(409,"Payment event was rejected.",{code:result.errorCode});return result;}
export async function simulate(userId,orderId,type){configured();if(env.nodeEnv!=="test")throw new ApiError(404,"Route not found.");const order=await model.getOrder(userId,orderId);if(!order||!order.provider_reference)throw new ApiError(404,"Sandbox checkout not found.");const event={eventId:`evt_${randomBytes(18).toString("hex")}`,type,providerReference:order.provider_reference,orderId:order.id,amountMinor:Number(order.total_minor),currency:order.currency};const raw=Buffer.from(JSON.stringify(event)),timestamp=String(Math.floor(Date.now()/1000)),signature=`sha256=${signPayload(raw,timestamp,env.sandboxPaymentWebhookSecret)}`;return webhook(raw,timestamp,signature);}
export async function receipt(userId,id){const row=await model.getOrder(userId,id);if(!row)throw new ApiError(404,"Order not found.");return{id:row.id,status:row.status,currency:row.currency,subtotalMinor:Number(row.subtotal_minor),discountMinor:Number(row.discount_minor),totalMinor:Number(row.total_minor),items:row.items,paymentStatus:row.payment_status,receiptNumber:row.receipt_number,issuedAt:row.issued_at};}
export default{initiate,webhook,simulate,receipt,signPayload,verifySignature};
