import { ApiError } from "../middleware/errorHandler.js";import * as model from "../models/projectSubmissionModel.js";
function map(row){return{id:row.id,userId:row.user_id,projectId:row.project_id,projectTitle:row.project_title,status:row.status,reviewerUserId:row.reviewer_user_id,learnerName:row.learner_name,version:row.version?{id:row.version_id,number:row.version,summary:row.summary,repositoryUrl:row.repository_url,demoUrl:row.demo_url,evidenceUrl:row.evidence_url,createdAt:row.version_created_at,submittedAt:row.submitted_at}:null,review:row.decision?{decision:row.decision,feedback:row.feedback,reviewerName:row.reviewer_name,reviewedAt:row.reviewed_at}:null,updatedAt:row.updated_at};}
async function detailPayload(row,ownerId=null){if(!row)throw new ApiError(404,"Project submission not found.");const[milestones,history]=await Promise.all([model.getMilestoneEvidence(row.version_id),model.getHistory(row.id,ownerId)]);return{submission:{...map(row),milestones:milestones.map(m=>({milestoneId:m.project_milestone_id,title:m.title,evidenceNote:m.evidence_note,evidenceUrl:m.evidence_url})),history:history.map(h=>({fromStatus:h.from_status,toStatus:h.to_status,note:h.note,actorName:h.actor_name,createdAt:h.created_at}))}};}
export async function saveDraft(userId,projectId,data){const project=await model.getEligibleProject(userId,projectId);if(!project)throw new ApiError(404,"Start this project before adding evidence.");if(project.user_status==="not_started")throw new ApiError(409,"Start this project before adding evidence.");const required=await model.getProjectMilestones(projectId);const allowed=new Set(required.map(m=>String(m.id)));const supplied=new Set(data.milestones.map(m=>String(m.milestoneId)));if(data.milestones.some(m=>!allowed.has(String(m.milestoneId))))throw new ApiError(400,"One or more milestones do not belong to this project.");if(required.some(m=>!supplied.has(String(m.id))))throw new ApiError(400,"Provide an evidence record for every required project milestone.");const result=await model.saveDraft(userId,projectId,data);if(result.blocked)throw new ApiError(409,`Evidence cannot be changed while the submission is ${result.blocked.replace("_"," ")}.`);await model.audit(userId,"project_submission.draft",result.submissionId,{version:result.version.version});return detailPayload(await model.getDetail(result.submissionId,userId),userId);}
export async function submit(userId,id){const result=await model.submit(userId,id);if(!result)throw new ApiError(404,"Project submission not found.");if(result.blocked)throw new ApiError(409,`Only a draft submission can be submitted for review.`);await model.audit(userId,"project_submission.submit",id);return detailPayload(await model.getDetail(id,userId),userId);}
export async function getMine(userId){return{submissions:(await model.listMine(userId)).map(map)};}
export async function getMineDetail(userId,id){return detailPayload(await model.getDetail(id,userId),userId);}
export async function queue(filters){const rows=await model.listQueue(filters);const total=rows[0]?.total||0;return{submissions:rows.map(map),pagination:{page:filters.page,limit:filters.limit,total,totalPages:Math.ceil(total/filters.limit)}};}
export async function reviewerDetail(id){const row=await model.getDetail(id);if(!row||row.status==="draft")throw new ApiError(404,"Project submission not found.");return detailPayload(row);}
export async function claim(actorId,id){const result=await model.claim(actorId,id);if(!result)throw new ApiError(404,"Project submission not found.");if(result.blocked)throw new ApiError(409,result.wrongReviewer?"Another reviewer is already handling this submission.":`This submission is already ${result.blocked}.`);if(!result.reused)await model.audit(actorId,"project_submission.claim",id);return reviewerDetail(id);}
export async function decide(actorId,id,{decision,feedback}){const result=await model.decide(actorId,id,decision,feedback);if(!result)throw new ApiError(404,"Project submission not found.");if(result.blocked){if(result.blocked===decision&&result.review?.feedback===feedback)return{...(await reviewerDetail(id)),reused:true};throw new ApiError(409,result.wrongReviewer?"Only the assigned reviewer can decide this submission.":`This submission is already ${result.blocked}.`);}await model.audit(actorId,`project_submission.${decision}`,id);return reviewerDetail(id);}
