import { useSearchParams } from "react-router-dom";
import { AccessBadge, UnlockButton } from "../../components/ui/ContentAccess.jsx";
import { useCallback,useEffect,useState } from "react";
import { Award,CheckCircle2,Download,RefreshCw,ShieldCheck } from "lucide-react";
import AppNav from "../../components/layout/AppNav.jsx";
import Button from "../../components/ui/Button.jsx";
import { Badge,Card } from "../../components/ui/Card.jsx";
import { ApiError } from "../../services/apiClient.js";
import * as api from "../../services/certificateService.js";
import "./CertificatesPage.css";

export default function CertificatesPage(){const[params]=useSearchParams();const productId=params.get("productId");const[state,setState]=useState({status:"loading",items:[],error:""});const[working,setWorking]=useState(null);const[notice,setNotice]=useState("");const load=useCallback(async()=>{setState(current=>({...current,status:"loading",error:""}));try{setState({status:"ready",items:await api.getCertificateCatalog(),error:""});}catch(error){setState({status:"error",items:[],error:error instanceof ApiError?error.message:"Could not load certificates."});}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);async function issue(id){setWorking(id);setNotice("");try{const result=await api.issueCertificate(id);setNotice(result.created?"Your completion certificate was issued.":"Your existing certificate is ready.");await load();}catch(error){setNotice(error instanceof ApiError?error.message:"Could not issue the certificate.");}finally{setWorking(null);}}
return <div><AppNav/><main id="main-content" tabIndex="-1" className="container sf-certificates"><header><p className="mono"><Award size={15}/> Completion certificates</p><h1>Verified SkillForge completion</h1><p>Certificates are available only after every configured requirement is recorded. They confirm SkillForge completion and are not an academic degree, professional license, or accredited qualification.</p></header>{notice&&<div className="sf-certificates__notice" role="status">{notice}</div>}{state.status==="loading"?<Card className="sf-certificates__state"><RefreshCw className="spin"/> Loading certificate programs…</Card>:state.status==="error"?<Card className="sf-certificates__state"><p>{state.error}</p><Button variant="secondary" onClick={load}>Try again</Button></Card>:state.items.length?<div className="sf-certificates__grid">{state.items.filter(item=>!productId||item.requiredProducts.some(p=>String(p.id)===productId)).map(item=><CertificateCard key={item.id} item={item} working={working===item.id} onIssue={()=>issue(item.id)}/>)}</div>:<Card className="sf-certificates__state"><ShieldCheck size={28}/><h2>No certificate programs are active</h2><p>An administrator must configure and activate requirements before a completion certificate can be issued.</p></Card>}</main></div>}
function CertificateCard({item,working,onIssue}){const e=item.eligibility;const certificate=item.certificate;return <Card className="sf-certificate-card"><div className="sf-certificate-card__head"><Award size={25}/><Badge tone={certificate?.status==="revoked"?"red":certificate?"teal":e.eligible?"blue":"neutral"}>{certificate?.status||`${e.readinessScore}/${e.requiredReadinessScore} readiness`}</Badge></div><AccessBadge item={item}/><h2>{item.title}</h2>{item.description&&<p>{item.description}</p>}<ul><Requirement label="Lessons" complete={item.lessons.length-e.missing.lessons.length} total={item.lessons.length}/><Requirement label="Quizzes" complete={item.quizzes.length-e.missing.quizzes.length} total={item.quizzes.length}/><Requirement label="Projects" complete={item.projects.length-e.missing.projects.length} total={item.projects.length}/></ul>{certificate?<div className="sf-certificate-card__actions"><Button href={api.certificatePdfUrl(certificate.verificationCode)} icon={<Download size={16}/>} iconPosition="left">Download PDF</Button><a href={`/certificates/verify/${certificate.verificationCode}`}>Public verification</a></div>:item.hasAccess===false?<UnlockButton item={item}/>:<Button disabled={!e.eligible||working} onClick={onIssue} icon={<Award size={16}/>} iconPosition="left">{working?"Issuing…":e.eligible?"Issue certificate":"Requirements incomplete"}</Button>}</Card>}
function Requirement({label,complete,total}){return <li><CheckCircle2 size={15}/><span>{label}</span><strong>{complete}/{total}</strong></li>}
