import { useRef, useCallback,useEffect,useState} from "react"; import {ArrowLeft,CheckCircle2,Clock3,Code2,Lightbulb,Send,Trophy} from "lucide-react"; import {useNavigate,useParams} from "react-router-dom"; import AppNav from "../../components/layout/AppNav.jsx"; import Button from "../../components/ui/Button.jsx"; import {Badge,Card} from "../../components/ui/Card.jsx"; import * as api from "../../services/challengeService.js"; import {ApiError} from "../../services/apiClient.js"; import "./ChallengeDetailsPage.css";
function ChallengeDetailsPageContent(){const{id}=useParams(),navigate=useNavigate();const[c,setC]=useState(null),[answer,setAnswer]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState("");const requestVersion = useRef(0);
const fetchData = useCallback(async () => {
    const version = ++requestVersion.current;
    const commit = (update) => { if (version === requestVersion.current) update(); };
    try{const result = await api.getChallenge(id); commit(() => setC(result))}catch(e){commit(() => setError(e instanceof ApiError?e.message:"Could not load this challenge."))}finally{commit(() => setLoading(false))}}, [id]);
  function load() {setLoading(true);setError("");return fetchData();
  }

useEffect(() => {
    fetchData();
    return () => { requestVersion.current += 1; };
  }, [fetchData]);async function submit(e){e.preventDefault();setBusy(true);setResult(null);setError("");try{const r=await api.submitChallenge(id,answer);setResult(r);if(r.correct)setC(x=>({...x,progress:{...x.progress,...r.progress}}))}catch(e){setError(e instanceof ApiError?e.message:"Could not submit your answer.")}finally{setBusy(false)}}if(loading)return <PageState text="Loading challenge…"/>;if(error&&!c)return <PageState text={error} error onRetry={load}/>;return <div><AppNav/><main id="main-content" tabIndex="-1" className="container sf-challenge-detail"><Button variant="ghost" onClick={()=>navigate("/challenges")} icon={<ArrowLeft size={15}/>}>Back to challenges</Button><header className="sf-challenge-detail__header"><div><div className="sf-challenge-detail__eyebrow"><Code2 size={15}/> Coding challenge</div><h1>{c.title}</h1><p>{c.description}</p><div className="sf-challenge-detail__badges"><Badge tone="blue">{c.difficulty}</Badge>{c.language&&<Badge tone="neutral">{c.language}</Badge>}<Badge tone="neutral"><Clock3 size={13}/> {c.estimatedMinutes} min</Badge>{c.progress?.status==="completed"&&<Badge tone="teal"><CheckCircle2 size={13}/> Completed</Badge>}</div></div></header>{error&&<Card className="sf-challenge-detail__alert">{error}</Card>}<div className="sf-challenge-detail__layout"><section><Card><h2>Challenge</h2><p className="sf-challenge-detail__instructions">{c.instructions}</p>{c.examples?.length>0&&<><h3>Examples</h3><div className="sf-challenge-detail__examples">{c.examples.map((x,i)=><div key={i}><span>Input</span><code>{x.input}</code><span>Output</span><code>{x.output}</code></div>)}</div></>}{c.starterCode&&<><h3>Starter code</h3><pre><code>{c.starterCode}</code></pre></>}<form onSubmit={submit}><label>Your answer<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Write your answer here…" rows={7} required/></label><Button type="submit" disabled={busy} icon={busy?<Send size={15}/>:<CheckCircle2 size={15}/>}>{busy?"Checking…":"Check answer"}</Button></form>{result&&<div className={`sf-challenge-detail__result ${result.correct?"correct":"incorrect"}`}><strong>{result.correct?<Trophy size={17}/>:<Lightbulb size={17}/>} {result.feedback}</strong>{!result.correct&&<p>Use the examples and hints, then try again.</p>}</div>}</Card></section><aside><Card><h3>Hints</h3>{(c.hints||[]).length?<ol>{c.hints.map((h,i)=><li key={i}>{h}</li>)}</ol>:<p>No hints for this challenge.</p>}<hr/><h3>Skills</h3><div className="sf-challenge-detail__skills">{(c.skills||[]).map(s=><Badge key={s.skillId} tone="neutral">{s.name}</Badge>)}</div><hr/><small>Attempts: {c.progress?.attemptsCount||0}</small></Card></aside></div></main></div>}
function PageState({text,error,onRetry}){return <div><AppNav/><main id="main-content" tabIndex="-1" className="container sf-challenge-detail__state"><Card><h2>{error?"Challenge unavailable":"Loading challenge"}</h2><p>{text}</p>{onRetry&&<Button variant="secondary" onClick={onRetry}>Try again</Button>}</Card></main></div>}

export default function ChallengeDetailsPage() {
  const { id } = useParams();
  return <ChallengeDetailsPageContent key={id} />;
}
