export const PUBLIC_SEO_ROUTES = [
  {path:'/',title:'SkillForge AI — Learn Job Skills and Build a Career Roadmap',description:'Explore practical technology skills, structured courses, career paths, projects, assessments, and personalized learning roadmaps with SkillForge AI.',heading:'Build practical skills for your next career',text:'Learn React, JavaScript, Python, SQL, Node.js, Git, HTML and CSS, and data structures through connected courses, projects, assessments, and career roadmaps.'},
  {path:'/skills',title:'Explore Technology and Career Skills | SkillForge AI',description:'Browse practical programming, data, design, marketing, and career skills. Find related learning resources and paths even if you are unsure of the exact skill name.',heading:'Explore practical skills',text:'Search programming, frontend, backend, data, design, business, marketing, and professional skills. Related topics help learners discover the right starting point.'},
  {path:'/courses',title:'Online Programming Courses and Learning Paths | SkillForge AI',description:'Browse structured React, JavaScript, Python, SQL, Node.js, Git, HTML and CSS, and algorithms courses with previews, projects, and assessments.',heading:'Structured online courses',text:'Study React development, JavaScript programming, Python, SQL databases, Node.js backend development, Git, HTML and CSS, and data structures and algorithms.'},
  {path:'/assessments',title:'Skill Assessments and Practice Questions | SkillForge AI',description:'Test practical programming knowledge with versioned assessments connected to SkillForge courses and learning paths.',heading:'Practical skill assessments',text:'Check your understanding of programming, web development, databases, version control, and algorithms with course-aligned questions.'},
  {path:'/store',title:'Skill Passes, Career Bundles and Monthly Access | SkillForge AI',description:'Compare one-time Skill Passes, Career Bundles, and 30-day all-access learning. Review exact included courses, projects, assessments, and certificate requirements.',heading:'Choose the learning access that fits your goal',text:'Choose one skill, a connected career bundle, or monthly access to all published premium learning content.'},
  {path:'/pricing',title:'SkillForge AI Pricing — Skill Pass, Career Bundle and Monthly',description:'Skill Pass PKR 999, Career Bundle PKR 1,999, and 30-day SkillForge Pro Monthly access PKR 649. Manual payment requires owner verification.',heading:'Clear SkillForge pricing',text:'Start free, buy permanent access to one skill or career bundle, or choose 30-day all-access. Review every included item before payment.'},
  {path:'/platform',title:'Career Learning Platform | SkillForge AI',description:'Understand the SkillForge platform for skill analysis, career planning, structured learning, projects, assessments, progress, and evidence.',heading:'One connected career learning platform',text:'Move from skill discovery to a practical roadmap, courses, portfolio projects, assessments, progress tracking, and completion evidence.'},
  {path:'/explore',title:'Explore SkillForge AI Learning Tools',description:'Explore SkillForge tools for skill discovery, career paths, learning roadmaps, daily missions, practical projects, and measurable progress.',heading:'Explore SkillForge AI',text:'Find the right skill, connect it to a career direction, follow a roadmap, practice through projects, and track meaningful progress.'},
  {path:'/how-it-works',title:'How SkillForge AI Works',description:'See how SkillForge connects your current skills, career direction, available time, courses, projects, and progress into a practical learning plan.',heading:'How SkillForge works',text:'Create an account, identify your goal, review skill gaps, follow a personalized roadmap, complete practical work, and measure progress.'},
  {path:'/skill-intelligence',title:'Skill Gap Analysis and Skill Intelligence | SkillForge AI',description:'Organize career requirements, identify skill gaps, and prioritize useful learning steps with transparent SkillForge skill intelligence.',heading:'Understand your skill gaps',text:'Compare current abilities with career requirements and find the programming, technical, and professional skills to learn next.'},
  {path:'/roadmaps',title:'Personalized Career and Learning Roadmaps | SkillForge AI',description:'Build a phased learning roadmap with skills, courses, projects, challenges, and milestones connected to your career direction.',heading:'Follow a personalized career roadmap',text:'Turn a broad career goal into ordered phases, weekly learning steps, practical projects, and measurable milestones.'},
  {path:'/privacy',title:'Privacy Policy | SkillForge AI',description:'Read how SkillForge handles account, learning, portfolio, and payment-proof information.',heading:'SkillForge privacy policy',text:'Learn what information is collected, why it is used, and how account and payment records are protected.'},
  {path:'/terms',title:'Terms of Use | SkillForge AI',description:'Read the terms that apply when using SkillForge learning, assessment, portfolio, certificate, and payment features.',heading:'SkillForge terms of use',text:'Understand the rules for accounts, learning content, payments, certificates, and responsible platform use.'},
  {path:'/refunds',title:'Refund Policy | SkillForge AI',description:'Review the SkillForge refund policy for manually verified Skill Pass, Career Bundle, and monthly access purchases.',heading:'SkillForge refund policy',text:'Review eligibility, evidence, timing, and access effects before requesting a refund.'},
];

export const PRIVATE_ROUTE_PREFIXES=['/admin','/dashboard','/checkout','/purchase','/purchases','/receipts','/my-access','/settings','/wallet','/onboarding','/learning','/assessments','/assessment-history','/submissions','/project-reviews','/course-admin','/quiz-admin','/progress','/portfolio','/readiness','/career-match','/careers','/projects','/certificates','/skill-analysis','/roadmap','/missions','/challenges'];
export const DEFAULT_SEO=PUBLIC_SEO_ROUTES[0];
