-- Curated starter catalog. URLs are deliberately stored here, reviewed as
-- trusted provider links, and never generated by the recommendation model.
BEGIN;

INSERT INTO learning_resources (skill_id, title, description, provider, resource_type, url, difficulty, estimated_hours, is_free)
SELECT s.id, v.title, v.description, v.provider, v.resource_type, v.url, v.difficulty, v.estimated_hours, v.is_free
FROM (VALUES
  ('HTML/CSS', 'Learn Web Development', 'Structured HTML and CSS learning modules with exercises.', 'MDN Web Docs', 'course', 'https://developer.mozilla.org/en-US/docs/Learn_web_development', 'beginner', 30, TRUE),
  ('JavaScript', 'JavaScript Guide', 'Official reference and guided JavaScript learning material.', 'MDN Web Docs', 'documentation', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide', 'beginner', 24, TRUE),
  ('React', 'Quick Start', 'Official React introduction with interactive examples.', 'React', 'tutorial', 'https://react.dev/learn', 'beginner', 12, TRUE),
  ('Node.js', 'Node.js Learn', 'Official Node.js learning guides and concepts.', 'Node.js', 'documentation', 'https://nodejs.org/en/learn', 'beginner', 12, TRUE),
  ('Python', 'The Python Tutorial', 'Official introduction to Python programming.', 'Python Software Foundation', 'tutorial', 'https://docs.python.org/3/tutorial/', 'beginner', 20, TRUE),
  ('SQL', 'PostgreSQL Tutorial', 'Official hands-on introduction to SQL and relational databases.', 'PostgreSQL', 'tutorial', 'https://www.postgresql.org/docs/current/tutorial.html', 'beginner', 12, TRUE),
  ('Git', 'Pro Git Book', 'The official free book for Git fundamentals and workflows.', 'Git', 'documentation', 'https://git-scm.com/book/en/v2', 'beginner', 16, TRUE),
  ('GitHub', 'Hello World', 'Official GitHub tutorial for repositories, branches, and pull requests.', 'GitHub Docs', 'tutorial', 'https://docs.github.com/en/get-started/start-your-journey/hello-world', 'beginner', 2, TRUE),
  ('TypeScript', 'TypeScript Handbook', 'Official TypeScript language handbook.', 'TypeScript', 'documentation', 'https://www.typescriptlang.org/docs/handbook/intro.html', 'beginner', 16, TRUE),
  ('Docker', 'Get Started with Docker', 'Official Docker fundamentals and container tutorial.', 'Docker Docs', 'tutorial', 'https://docs.docker.com/get-started/', 'beginner', 8, TRUE),
  ('CI/CD', 'GitHub Actions Documentation', 'Official guides for automating build, test, and deployment workflows.', 'GitHub Docs', 'documentation', 'https://docs.github.com/en/actions', 'intermediate', 12, TRUE),
  ('Cloud Computing (AWS/Azure/GCP)', 'Microsoft Learn Training', 'Free cloud learning paths and hands-on modules.', 'Microsoft Learn', 'course', 'https://learn.microsoft.com/training/', 'beginner', 16, TRUE),
  ('Linux/CLI', 'The Linux Command Line', 'Free command-line learning book from LinuxCommand.org.', 'LinuxCommand.org', 'tutorial', 'https://linuxcommand.org/tlcl.php', 'beginner', 16, TRUE),
  ('REST API Design', 'Using the Fetch API', 'Official guide to making web API requests.', 'MDN Web Docs', 'documentation', 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch', 'intermediate', 6, TRUE),
  ('Unit Testing', 'Jest Getting Started', 'Official introduction to JavaScript testing with Jest.', 'Jest', 'tutorial', 'https://jestjs.io/docs/getting-started', 'beginner', 6, TRUE),
  ('Test Automation', 'Playwright Introduction', 'Official end-to-end testing introduction.', 'Playwright', 'tutorial', 'https://playwright.dev/docs/intro', 'intermediate', 10, TRUE),
  ('Data Structures & Algorithms', 'JavaScript Algorithms and Data Structures', 'Free interactive practice curriculum.', 'freeCodeCamp', 'practice', 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/', 'beginner', 40, TRUE),
  ('Machine Learning', 'Machine Learning Crash Course', 'Google''s practical introduction to machine learning.', 'Google for Developers', 'course', 'https://developers.google.com/machine-learning/crash-course', 'beginner', 15, TRUE),
  ('ML Frameworks (TensorFlow/PyTorch)', 'TensorFlow Tutorials', 'Official hands-on TensorFlow tutorials.', 'TensorFlow', 'tutorial', 'https://www.tensorflow.org/tutorials', 'intermediate', 20, TRUE),
  ('Statistics', 'Khan Academy Statistics and Probability', 'Free foundational statistics lessons and practice.', 'Khan Academy', 'course', 'https://www.khanacademy.org/math/statistics-probability', 'beginner', 24, TRUE),
  ('Data Analysis (Pandas)', 'Getting Started Tutorials', 'Official pandas tutorials for tabular data analysis.', 'pandas', 'tutorial', 'https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html', 'beginner', 12, TRUE),
  ('Data Visualization', 'Matplotlib Tutorials', 'Official plotting tutorials and examples.', 'Matplotlib', 'tutorial', 'https://matplotlib.org/stable/tutorials/index.html', 'beginner', 10, TRUE),
  ('Kotlin', 'Android Basics with Compose', 'Official Android learning path for Kotlin and modern Android UI.', 'Android Developers', 'course', 'https://developer.android.com/courses/android-basics-compose/course', 'beginner', 40, TRUE),
  ('Swift', 'The Swift Programming Language', 'Official Swift language documentation.', 'Swift', 'documentation', 'https://docs.swift.org/swift-book/documentation/the-swift-programming-language/', 'beginner', 20, TRUE),
  ('Mobile Development (React Native/Flutter)', 'React Native Environment Setup', 'Official setup guide for React Native development.', 'React Native', 'tutorial', 'https://reactnative.dev/docs/set-up-your-environment', 'beginner', 6, TRUE),
  ('UI Design Tools (Figma)', 'Figma Resource Library', 'Official Figma learning resources and tutorials.', 'Figma', 'tutorial', 'https://www.figma.com/resource-library/', 'beginner', 8, TRUE),
  ('UX Research', 'UX Research Field Guide', 'Practical research methods and planning guidance.', 'Nielsen Norman Group', 'tutorial', 'https://www.nngroup.com/articles/ux-research-cheat-sheet/', 'beginner', 6, TRUE),
  ('Wireframing & Prototyping', 'Figma Resource Library', 'Official guides for designing and prototyping in Figma.', 'Figma', 'tutorial', 'https://www.figma.com/resource-library/', 'beginner', 8, TRUE),
  ('Design Systems', 'Design Systems Handbook', 'Open design-systems learning handbook.', 'InVision', 'documentation', 'https://www.designbetter.co/design-systems-handbook', 'intermediate', 12, TRUE),
  ('Cybersecurity Fundamentals', 'OWASP Top 10', 'Official awareness document for common web application security risks.', 'OWASP', 'documentation', 'https://owasp.org/www-project-top-ten/', 'beginner', 8, TRUE),
  ('Penetration Testing', 'Web Security Testing Guide', 'OWASP guide for authorized web security testing.', 'OWASP', 'documentation', 'https://owasp.org/www-project-web-security-testing-guide/', 'advanced', 24, TRUE),
  ('Networking Fundamentals', 'Networking Basics', 'Free networking fundamentals learning path.', 'Cisco Networking Academy', 'course', 'https://www.netacad.com/courses/networking-basics', 'beginner', 22, TRUE),
  ('Game Development (Unity/Unreal)', 'Unity Learn', 'Official guided projects and pathways for Unity.', 'Unity', 'project', 'https://learn.unity.com/', 'beginner', 20, TRUE),
  ('Project Management', 'Project Management Guide', 'Free practical project-management guides and templates.', 'Atlassian', 'tutorial', 'https://www.atlassian.com/work-management/project-management', 'beginner', 8, TRUE),
  ('Agile/Scrum', 'Agile Tutorials', 'Practical Agile and Scrum tutorials from Atlassian.', 'Atlassian', 'tutorial', 'https://www.atlassian.com/agile/tutorials', 'beginner', 8, TRUE),
  ('Google Analytics', 'Google Analytics Skillshop', 'Official Google Analytics learning and certification paths.', 'Google Skillshop', 'course', 'https://skillshop.withgoogle.com/', 'beginner', 12, TRUE),
  ('SEO', 'SEO Starter Guide', 'Official introductory guidance for search engine optimization.', 'Google Search Central', 'documentation', 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide', 'beginner', 8, TRUE),
  ('Content Marketing', 'HubSpot Academy Content Marketing', 'Free content-marketing course and certification.', 'HubSpot Academy', 'course', 'https://academy.hubspot.com/courses/content-marketing', 'beginner', 10, TRUE),
  ('Email Marketing', 'HubSpot Academy Email Marketing', 'Free email-marketing course and certification.', 'HubSpot Academy', 'course', 'https://academy.hubspot.com/courses/email-marketing', 'beginner', 8, TRUE),
  ('Photography', 'Adobe Photography Tutorials', 'Official photography and editing tutorials.', 'Adobe', 'video', 'https://helpx.adobe.com/photoshop/tutorials.html', 'beginner', 10, TRUE),
  ('Video Editing', 'Adobe Premiere Pro Tutorials', 'Official Premiere Pro tutorials.', 'Adobe', 'video', 'https://helpx.adobe.com/premiere-pro/tutorials.html', 'beginner', 12, TRUE),
  ('Adobe Photoshop', 'Adobe Photoshop Tutorials', 'Official Photoshop tutorials and guided practice.', 'Adobe', 'tutorial', 'https://helpx.adobe.com/photoshop/tutorials.html', 'beginner', 12, TRUE),
  ('Adobe Illustrator', 'Adobe Illustrator Tutorials', 'Official Illustrator tutorials and guided practice.', 'Adobe', 'tutorial', 'https://helpx.adobe.com/illustrator/tutorials.html', 'beginner', 12, TRUE),
  ('Communication', 'Effective Communication', 'Free communication skills course.', 'OpenLearn', 'course', 'https://www.open.edu/openlearn/health-sports-psychology/communication-skills/content-section-overview', 'beginner', 8, TRUE),
  ('Technical Writing', 'Google Technical Writing Courses', 'Free technical-writing courses from Google.', 'Google for Developers', 'course', 'https://developers.google.com/tech-writing', 'beginner', 12, TRUE),
  ('Research Methods', 'SAGE Research Methods Foundations', 'Introductory research-methods learning materials.', 'SAGE Campus', 'tutorial', 'https://methods.sagepub.com/foundations', 'beginner', 12, TRUE),
  ('Financial Analysis', 'Financial Markets', 'Free university financial-markets course.', 'Yale University', 'course', 'https://oyc.yale.edu/economics/econ-252-11', 'beginner', 24, TRUE)
) AS v(skill_name, title, description, provider, resource_type, url, difficulty, estimated_hours, is_free)
JOIN skills s ON s.name = v.skill_name
ON CONFLICT (skill_id, url) DO NOTHING;

COMMIT;
