import { useEffect } from "react";
import { Flag, Route, Wrench, BarChart3, ArrowRight, Map } from "lucide-react";
import Button from "../../components/ui/Button.jsx";
import { setPageMeta } from "../../utils/seo.js";
import "./PublicMarketingPage.css";
const steps=[["Start from priorities","A roadmap begins with the skills and requirements that matter to your direction."],["Move through phases","Break larger growth into manageable phases instead of one overwhelming checklist."],["Build evidence","Use projects and challenges to turn learning into practical output."],["Review progress","Track completed work and use that information to plan the next stage."]];
export default function RoadmapsPage(){
 useEffect(()=>setPageMeta({title:"Career roadmaps",description:"Explore how SkillForge AI organizes career growth into phases, projects, challenges, and measurable progress."}),[]);
 return <section className="public-page"><div className="container"><header className="public-page__hero"><span className="public-page__eyebrow"><Map size={16}/> Personalized roadmaps</span><h1>Turn a large career goal into a path you can follow.</h1><p>Roadmaps connect skill priorities with phases and practical work so you can see both the bigger direction and the next manageable action.</p><div className="public-page__actions"><Button variant="primary" size="lg" to="/signup">Build my roadmap <ArrowRight size={18}/></Button><Button variant="secondary" size="lg" to="/skill-intelligence">Skill intelligence</Button></div></header><div className="public-grid">{[[Flag,"Career direction","Keep the roadmap connected to the outcome you are working toward."],[Route,"Structured phases","Organize growth into stages that are easier to understand and complete."],[Wrench,"Practical work","Connect phases to projects, challenges, and focused tasks."],[BarChart3,"Visible progress","Review completed work and maintain momentum over time."]].map(([Icon,title,text])=><article className="public-card" key={title}><span className="public-card__icon"><Icon size={23}/></span><h2>{title}</h2><p>{text}</p></article>)}</div><section className="public-section"><h2>A roadmap is a sequence, not a static list.</h2><p>Use it as a working plan: understand the current phase, complete focused work, then move forward with more evidence and context.</p><div className="public-steps">{steps.map(([a,b])=><div className="public-step" key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></section></div></section>;
}