import { useCallback,useEffect,useState } from "react";
import { Award,Download,Search,ShieldAlert,ShieldCheck } from "lucide-react";
import { Link,useNavigate,useParams } from "react-router-dom";
import Button from "../../components/ui/Button.jsx";
import { Card } from "../../components/ui/Card.jsx";
import { ApiError } from "../../services/apiClient.js";
import * as api from "../../services/certificateService.js";
import "../app/CertificatesPage.css";
export default function CertificateVerificationPage(){const{code}=useParams();const navigate=useNavigate();const[input,setInput]=useState(code||"");const[state,setState]=useState({status:"loading",data:null,error:""});const load=useCallback(async()=>{setState({status:"loading",data:null,error:""});try{setState({status:"ready",data:await api.verifyCertificate(code),error:""});}catch(error){setState({status:"error",data:null,error:error instanceof ApiError?error.message:"Certificate verification is unavailable."});}},[code]);useEffect(()=>{void Promise.resolve().then(load);},[load]);function submit(event){event.preventDefault();const clean=input.trim();if(clean)navigate(`/certificates/verify/${encodeURIComponent(clean)}`);}const data=state.data;return <main className="sf-verification"><Link className="sf-verification__brand" to="/"><Award size={22}/> SkillForge AI</Link><Card className="sf-verification__card"><form onSubmit={submit}><label htmlFor="verification-code">Verification code</label><div><input id="verification-code" value={input} onChange={event=>setInput(event.target.value)} maxLength="32"/><Button type="submit" icon={<Search size={16}/>} iconPosition="left">Verify</Button></div></form>{state.status==="loading"&&<p>Checking the certificate…</p>}{state.status==="error"&&<section className="sf-verification__result sf-verification__result--error"><ShieldAlert/><h1>Certificate not verified</h1><p>{state.error}</p></section>}{data&&<section className={`sf-verification__result${data.status==="revoked"?" sf-verification__result--error":""}`}>{data.status==="active"?<ShieldCheck/>:<ShieldAlert/>}<p className="mono">{data.status==="active"?"ACTIVE CERTIFICATE":"REVOKED CERTIFICATE"}</p><h1>{data.recipientName}</h1><h2>{data.title}</h2><p>Issued {new Date(data.issuedAt).toLocaleDateString()}</p>{data.revokedAt&&<p>Revoked {new Date(data.revokedAt).toLocaleDateString()}</p>}<p>{data.disclosure}</p><Button variant="secondary" href={api.certificatePdfUrl(data.verificationCode)} icon={<Download size={16}/>} iconPosition="left">Download PDF</Button></section>}</Card></main>}
